# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lolzinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.EmailField(max_length=120, unique=True)),
                ('nick', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('rank_position', models.CharField(max_length=10, null=True)),
                ('league', models.CharField(default=b'unranked', max_length=10)),
                ('numQuestions', models.IntegerField(default=0)),
                ('cQuestions', models.IntegerField(default=0)),
                ('photo', models.FileField(default=0, upload_to=b'avatars')),
                ('winrate', models.FloatField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
