# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lolzinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('league', models.CharField(default=b'unranked', max_length=10)),
                ('numQuestions', models.IntegerField(default=0)),
                ('cQuestions', models.IntegerField(default=0)),
                ('photo', models.FileField(default=0, upload_to=b'lolzin/avatars')),
                ('winrate', models.FloatField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
