# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolzin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lolzinuser',
            name='photo',
            field=models.FileField(default=0, upload_to=b'lolzin/avatars'),
        ),
    ]
